version: '3.7'

services:
    grafana:
        image: grafana/grafana:7.0.0
        volumes:
            - ./:/var/lib/grafana/plugins/sensor-data-source
        environment:
            GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "kwm-sys-sensor-data-source"
            GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
            GF_AUTH_GENERIC_OAUTH_NAME: "KWMSys"
            GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
            GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "grafana"
            GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${GRAFANA_OAUTH_SECRET}
            GF_AUTH_GENERIC_OAUTH_SCOPES: "profile sdp"
            GF_AUTH_GENERIC_OAUTH_AUTH_URL: ${KEYCLOAK_AUTH_URL}
            GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ${KEYCLOAK_TOKEN_URL}
            GF_AUTH_GENERIC_OAUTH_API_URL: ${KEYCLOAK_USERINFO_URL}
            GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'"
            GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_STRICT: "true"
        ports: 
            - 3000:3000