version: '3.7'

services:
    grafana:
        image: grafana/grafana:7.0.0
        volumes:
            - ./:/var/lib/grafana/plugins/sensor-data-source
        environment:
            GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "kwm-sys-sensor-data-source"
        ports: 
            - 3000:3000